apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: tcp
        env:
# MARIADB_HOST
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MARIADB_HOST
# MARIADB_PORT
        - name: MARIADB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MARIADB_PORT
# MARIADB_ROOT_PASSWORD
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_ROOT_PASSWORD
# MARIADB_DATABASE
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_DATABASE
# MARIADB_USER
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_USER
# MARIADB_PASSWORD
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: mariadb-init-sql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 1Gi